# Generated by Django 5.0.6 on 2026-05-11 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(upload_to='destinations/')),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(default='Bangladesh', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('best_season', models.CharField(choices=[('year_round', 'Year Round'), ('summer', 'Summer (Mar–Jun)'), ('monsoon', 'Monsoon (Jul–Oct)'), ('winter', 'Winter (Nov–Feb)'), ('autumn', 'Autumn (Sep–Nov)')], default='winter', max_length=20)),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weather_info', models.TextField(blank=True)),
                ('safety_tips', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-view_count'],
                'indexes': [models.Index(fields=['slug'], name='destination_slug_528bb8_idx'), models.Index(fields=['is_featured', 'is_active'], name='destination_is_feat_30ec6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to='destinations.destination')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('destination', 'author')},
            },
        ),
    ]
