# Generated by Django 5.0.6 on 2026-05-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
