# Generated by Django 5.0.6 on 2026-05-11 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fa-map-marked-alt', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='tour_categories/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tour Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('duration_nights', models.PositiveIntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight'), ('boat', 'Boat'), ('private_car', 'Private Car'), ('mixed', 'Mixed Transport')], default='bus', max_length=20)),
                ('transport_details', models.TextField(blank=True)),
                ('hotel_name', models.CharField(blank=True, max_length=200)),
                ('hotel_details', models.TextField(blank=True)),
                ('included_services', models.TextField(blank=True, help_text='One item per line')),
                ('excluded_services', models.TextField(blank=True, help_text='One item per line')),
                ('food_details', models.TextField(blank=True)),
                ('guide_available', models.BooleanField(default=True)),
                ('seats_total', models.PositiveIntegerField(default=30)),
                ('seats_booked', models.PositiveIntegerField(default=0)),
                ('featured_image', models.ImageField(upload_to='tours/')),
                ('video_url', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold_out', 'Sold Out'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='tours.tourcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tours', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='destinations.destination')),
            ],
            options={
                'ordering': ['-is_featured', '-is_popular', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tours.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_reviews', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_reviews', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['slug'], name='tours_tourp_slug_0bb879_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['status', 'is_featured'], name='tours_tourp_status_c29b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['category'], name='tours_tourp_categor_487315_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='touritinerary',
            unique_together={('tour', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='tourreview',
            unique_together={('tour', 'author')},
        ),
    ]
